### ISSUE TITLE
大佬请教您一下有时订阅无法推送的情况

### ISSUE THREAD

**Issue by xia0ti** [Sora233/bilidynamicpush#3]
报错如下：
[2021-10-30 18:28:03,093 bili-dynamic] INFO: B站直播检查发生错误 uid=11808975
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\jubot\HoshinoBot\hoshino\modules\bilidynamicpush\push.py", line 449, in check_bili_dynamic
    if res['data']['liveStatus'] == 1 and not room_states[uid]:
TypeError: 'NoneType' object is not subscriptable

[2021-10-30 18:28:03,172 bili-dynamic] INFO: B站直播检查发生错误 uid=4410876
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\jubot\HoshinoBot\hoshino\modules\bilidynamicpush\push.py", line 449, in check_bili_dynamic
    if res['data']['liveStatus'] == 1 and not room_states[uid]:
TypeError: 'NoneType' object is not subscriptable

之前可用，突然间无法推送，重装或重新订阅都无法解决，不知道遇到了什么问题。

**Comment by xia0ti** [comment]
视频动态可以推送，目前只有直播状态报错。

**Comment by Sora233** [comment]
b站更新api，部分老api故障

**Comment by xia0ti** [comment]
> b站更新api，部分老api故障

非常感谢！
