### ISSUE TITLE
寄了，订阅所有UID都显示用户不存在

### ISSUE THREAD

**Issue by tuanzi66** [Sora233/bilidynamicpush#9]

**Comment by Sora233** [comment]
可以提供下日志么

**Comment by xia0ti** [comment]
> 

[2022-07-01 14:22:14,945 nonebot] INFO: Self: 1399439510, Message 800963549 from 4987388@[群:723258962]: '订阅动态 1820232 324125073'
[2022-07-01 14:22:14,945 bili-dynamic] INFO: Message 800963549 triggered subscribe_dynamic by PrefixTrigger.
[2022-07-01 14:22:15,094 nonebot] INFO: Self: 1399439510, Message 1588813477 from 452746697@[群:985686454]: '[CQ:face,id=317,type=sticker]'
[2022-07-01 14:22:15,436 nonebot] INFO: Message 800963549 is ignored
[2022-07-01 14:22:15,936 bili-dynamic] INFO: B站动态检查结束
[2022-07-01 14:22:15,936 bili-dynamic] INFO: B站直播状态检查开始
[2022-07-01 14:22:17,793 bili-dynamic] INFO: B站直播检查发生错误 uid=703007996
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\jubot\HoshinoBot\hoshino\modules\bilidynamicpush\push.py", line 449, in check_bili_dynamic
    if res['data']['live_room']['liveStatus'] == 1 and not room_states[uid]:
TypeError: 'NoneType' object is not subscriptable

[2022-07-01 14:22:17,949 bili-dynamic] INFO: B站直播检查发生错误 uid=672342685
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\jubot\HoshinoBot\hoshino\modules\bilidynamicpush\push.py", line 449, in check_bili_dynamic
    if res['data']['live_room']['liveStatus'] == 1 and not room_states[uid]:
TypeError: 'NoneType' object is not subscriptable

[2022-07-01 14:22:18,137 bili-dynamic] INFO: B站直播检查发生错误 uid=672328094
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\jubot\HoshinoBot\hoshino\modules\bilidynamicpush\push.py", line 449, in check_bili_dynamic
    if res['data']['live_room']['liveStatus'] == 1 and not room_states[uid]:
TypeError: 'NoneType' object is not subscriptable

[2022-07-01 14:22:18,310 bili-dynamic] INFO: B站直播检查发生错误 uid=40665101
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\jubot\HoshinoBot\hoshino\modules\bilidynamicpush\push.py", line 449, in check_bili_dynamic
    if res['data']['live_room']['liveStatus'] == 1 and not room_states[uid]:
TypeError: 'NoneType' object is not subscriptable

[2022-07-01 14:22:18,450 bili-dynamic] INFO: B站直播检查发生错误 uid=82800638
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\jubot\HoshinoBot\hoshino\modules\bilidynamicpush\push.py", line 449, in check_bili_dynamic
    if res['data']['live_room']['liveStatus'] == 1 and not room_states[uid]:
TypeError: 'NoneType' object is not subscriptable

[2022-07-01 14:22:18,607 bili-dynamic] INFO: B站直播检查发生错误 uid=353240497
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\jubot\HoshinoBot\hoshino\modules\bilidynamicpush\push.py", line 449, in check_bili_dynamic
    if res['data']['live_room']['liveStatus'] == 1 and not room_states[uid]:
TypeError: 'NoneType' object is not subscriptable

[2022-07-01 14:22:18,747 bili-dynamic] INFO: B站直播检查发生错误 uid=11808975
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\jubot\HoshinoBot\hoshino\modules\bilidynamicpush\push.py", line 449, in check_bili_dynamic
    if res['data']['live_room']['liveStatus'] == 1 and not room_states[uid]:
TypeError: 'NoneType' object is not subscriptable

[2022-07-01 14:22:18,903 bili-dynamic] INFO: B站直播检查发生错误 uid=4410876
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\jubot\HoshinoBot\hoshino\modules\bilidynamicpush\push.py", line 449, in check_bili_dynamic
    if res['data']['live_room']['liveStatus'] == 1 and not room_states[uid]:
TypeError: 'NoneType' object is not subscriptable

[2022-07-01 14:22:19,075 bili-dynamic] INFO: B站直播检查发生错误 uid=519465407
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\jubot\HoshinoBot\hoshino\modules\bilidynamicpush\push.py", line 449, in check_bili_dynamic
    if res['data']['live_room']['liveStatus'] == 1 and not room_states[uid]:
TypeError: 'NoneType' object is not subscriptable

[2022-07-01 14:22:19,232 bili-dynamic] INFO: B站直播检查发生错误 uid=1994753
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\jubot\HoshinoBot\hoshino\modules\bilidynamicpush\push.py", line 449, in check_bili_dynamic
    if res['data']['live_room']['liveStatus'] == 1 and not room_states[uid]:
TypeError: 'NoneType' object is not subscriptable

[2022-07-01 14:22:19,419 bili-dynamic] INFO: B站直播检查发生错误 uid=2899906
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\jubot\HoshinoBot\hoshino\modules\bilidynamicpush\push.py", line 449, in check_bili_dynamic
    if res['data']['live_room']['liveStatus'] == 1 and not room_states[uid]:
TypeError: 'NoneType' object is not subscriptable

[2022-07-01 14:22:19,591 bili-dynamic] INFO: B站直播检查发生错误 uid=2866621
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\jubot\HoshinoBot\hoshino\modules\bilidynamicpush\push.py", line 449, in check_bili_dynamic
    if res['data']['live_room']['liveStatus'] == 1 and not room_states[uid]:
TypeError: 'NoneType' object is not subscriptable

[2022-07-01 14:22:19,747 bili-dynamic] INFO: B站直播检查发生错误 uid=533230
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\jubot\HoshinoBot\hoshino\modules\bilidynamicpush\push.py", line 449, in check_bili_dynamic
    if res['data']['live_room']['liveStatus'] == 1 and not room_states[uid]:
TypeError: 'NoneType' object is not subscriptable

[2022-07-01 14:22:19,905 bili-dynamic] INFO: B站直播检查发生错误 uid=586223
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\jubot\HoshinoBot\hoshino\modules\bilidynamicpush\push.py", line 449, in check_bili_dynamic
    if res['data']['live_room']['liveStatus'] == 1 and not room_states[uid]:
TypeError: 'NoneType' object is not subscriptable

[2022-07-01 14:22:20,093 bili-dynamic] INFO: B站直播检查发生错误 uid=22524715
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\jubot\HoshinoBot\hoshino\modules\bilidynamicpush\push.py", line 449, in check_bili_dynamic
    if res['data']['live_room']['liveStatus'] == 1 and not room_states[uid]:
TypeError: 'NoneType' object is not subscriptable


大佬帮忙看一下吧。相同的情况，新订阅会显示订阅失败用户不存在。已经订阅的用户，群里并没有动态消息。之前一切正常。

**Comment by thankU-ubi** [comment]
[2022-07-05 02:13:45,852 bili-dynamic] INFO: Message 1988624407 triggered subscribe_dynamic.
[2022-07-05 02:13:46,231 nonebot] INFO: Message 1988624407 is ignored: Handled by Hoshino
[2022-07-05 02:14:00,295 bili-dynamic] INFO: Scheduled job check_bili_dynamic start.
[2022-07-05 02:14:00,296 bili-dynamic] INFO: B站动态检查开始
[2022-07-05 02:14:00,748 bili-dynamic] INFO: B站动态检查结束
[2022-07-05 02:14:00,748 bili-dynamic] INFO: B站直播状态检查开始
[2022-07-05 02:14:00,904 bili-dynamic] INFO: B站直播检查发生错误 uid=15264115
Traceback (most recent call last):
  File "D:\hoshinoBOT\HoshinoBot\hoshino\modules\bilidynamicpush\push.py", line 449, in check_bili_dynamic
    if res['data']['live_room']['liveStatus'] == 1 and not room_states[uid]:
TypeError: 'NoneType' object is not subscriptable
[2022-07-05 02:14:00,904 bili-dynamic] INFO: B站直播状态检查结束
[2022-07-05 02:14:00,905 bili-dynamic] INFO: Scheduled job check_bili_dynamic completed.

都一样，估计是B站的问题把

**Comment by thankU-ubi** [comment]
很奇怪的是，BOT能正常推送下播消息

**Comment by xia0ti** [comment]
> 很奇怪的是，BOT能正常推送下播消息

我这边下播消息是延迟几个小时推送的，并不是当时。

**Comment by chenchenriver** [comment]
d

**Comment by thankU-ubi** [comment]
圣嘉然何时能修复issues😭
